Repository omisego/ios-sdk, pull requests merged in 2018-05, with the labels that each got.

#46 Refactor RequestBuilder and Endpoint
  AUTHORS
  OmiseGO.xcodeproj/project.pbxproj
  OmiseGOTests/APITests/RequestBuilderTests.swift
  OmiseGOTests/APITests/RequestParametersTests.swift
  OmiseGOTests/FixtureTests/FixtureClient.swift
  OmiseGOTests/FixtureTests/LogoutFixtureTests.swift
  OmiseGOTests/FixtureTests/RequestFixtureTest.swift
  OmiseGOTests/HTTPTests/APIEndpointTest.swift
  OmiseGOTests/HTTPTests/RequestTest.swift
  OmiseGOTests/Helpers/DummyObject.swift
  OmiseGOTests/Helpers/MetadataDummy.swift
  OmiseGOTests/ModelTests/TransactionConsumptionParamsTest.swift
  Source/API/APIEndpoint.swift
  Source/API/HTTPTask.swift
  Source/API/Request.swift
  Source/API/RequestBuilder.swift
  Source/API/RequestParameters.swift
  Source/Models/PaginationParams.swift
  Source/Models/TransactionConsumptionParams.swift
  Source/Models/TransactionListParams.swift
  Source/Models/TransactionRequestParams.swift
  Source/Websocket/SocketClient.swift
  Source/Websocket/SocketPayload.swift
Labels: enhancement

#48 T281 max consumption per user
  OmiseGOTests/APITests/APIErrorTests.swift
  OmiseGOTests/CodingTests/EncodeTests.swift
  OmiseGOTests/FixtureTests/Fixtures/fixture/me.approve_transaction_consumption.json
  OmiseGOTests/FixtureTests/Fixtures/fixture/me.consume_transaction_request.json
  OmiseGOTests/FixtureTests/Fixtures/fixture/me.create_transaction_request.json
  OmiseGOTests/FixtureTests/Fixtures/fixture/me.get_transaction_request.json
  OmiseGOTests/FixtureTests/Fixtures/fixture/me.reject_transaction_consumption.json
  OmiseGOTests/FixtureTests/Fixtures/objects/socket_response.json
  OmiseGOTests/FixtureTests/Fixtures/objects/transaction_consumption.json
  OmiseGOTests/FixtureTests/Fixtures/objects/transaction_request.json
  OmiseGOTests/Helpers/StubGenerator.swift
  OmiseGOTests/LiveTests/TransactionRequestLiveTests.swift
  OmiseGOTests/ModelTests/TransactionConsumptionParamsTest.swift
  OmiseGOTests/ModelTests/TransactionRequestParamsTest.swift
  README.md
  Source/API/APIError.swift
  Source/Models/TransactionRequest.swift
  Source/Models/TransactionRequestParams.swift
Labels: Feature

#49 Rename Address model to Wallet
  OmiseGO.xcodeproj/project.pbxproj
  OmiseGOTests/CodingTests/DecodeTests.swift
  OmiseGOTests/FixtureTests/Fixtures/fixture/me.list_wallets.json
  OmiseGOTests/FixtureTests/Fixtures/objects/wallet.json
  OmiseGOTests/FixtureTests/WalletFixtureTests.swift
  OmiseGOTests/HTTPTests/APIEndpointTest.swift
  OmiseGOTests/Helpers/StubGenerator.swift
  OmiseGOTests/LiveTests/WalletLiveTests.swift
  OmiseGOTests/ModelTests/WalletTests.swift
  README.md
  Source/API/APIEndpoint.swift
  Source/Models/TransactionListParams.swift
  Source/Models/TransactionRequestParams.swift
  Source/Models/Wallet.swift
Labels: Refactor

#51 T307 me.transfer
  OmiseGO.podspec
  OmiseGO.xcodeproj/project.pbxproj
  OmiseGOTests/APITests/APIErrorTests.swift
  OmiseGOTests/CodingTests/EncodeTests.swift
  OmiseGOTests/FixtureTests/Fixtures/fixture/me.transfer.json
  OmiseGOTests/FixtureTests/TransactionFixtureTests.swift
  README.md
  Source/API/APIEndpoint.swift
  Source/API/APIError.swift
  Source/Info.plist
  Source/Models/Transaction.swift
  Source/Models/TransactionParams.swift
Labels: enhancement

#54 Add more attributes to Wallet
  OmiseGOTests/CodingTests/DecodeTests.swift
  OmiseGOTests/FixtureTests/Fixtures/fixture/me.list_wallets.json
  OmiseGOTests/FixtureTests/Fixtures/objects/wallet.json
  OmiseGOTests/FixtureTests/WalletFixtureTests.swift
  OmiseGOTests/Helpers/StubGenerator.swift
  Source/Models/Wallet.swift
Labels: enhancement
